### ISSUE TITLE
Servers are down? Can't log in to the app (Server Error 503)

### ISSUE THREAD

**Issue by krishaamer** [letsdoitworld/World-Cleanup-Day#137]
Can't log in to the app, stuck on the first screen.

![img_3322](https://user-images.githubusercontent.com/54409/34358305-8bde6cdc-ea46-11e7-84b0-979fa3377bb7.PNG)

Status (Dec 26): Qualitance has been notified and they will start investigating tomorrow.

**Comment by KristiinaKerge** [comment]
On 26th of December at 12.50 the app had critical issues - can't log in with Facebook, can't log in with Google, can't view without logging in, no trashpoints. Error 503 appears to the screen. 
I tested with 3 phones and all of them had the same error 503. Error occurs with Android ver 7.1.1, ver 8.0.0 and iOS 11.0.3 phones.

**Comment by rionita** [comment]
fixed by rebooting the proxy.
a crashed service was blocking the login.
we need to add some sort of monitoring on the login, this is the only one not covered at the moment

**Comment by iiasunshine** [comment]
Hi Radu,
I can login but I cannot see the piles. I received error 400.

**Comment by kadry55** [comment]
![screenshot_20171228-102354](https://user-images.githubusercontent.com/30211382/34405018-a33cfeba-ebb9-11e7-9328-015695e7e021.png)
Still getting error 503 when moving on map. Also, when adding trashpoint i get error 500 after making the photo.
![screenshot_20171228-102354](https://user-images.githubusercontent.com/30211382/34405010-948eb5ca-ebb9-11e7-92a6-af6b46871e9e.png)

**Comment by rionita** [comment]
main login issue encountered in the past days is fixed.
the other errors are known existing issues, for which we don't have a root cause at the moment.
they need to be investigated and estimated, but it's not something that can be easily reproduced and fixed.

**Comment by kadry55** [comment]
Same issue as #135 . @rionita - do you know how long was the downtime?

**Comment by krishaamer** [comment]
We need to create a service status page for these kind of large failures. The downtime was at least 2 days?
