### ISSUE TITLE
To view the trashpoint photos in full screen

### ISSUE THREAD

**Issue by KristiinaKerge** [letsdoitworld/World-Cleanup-Day#95]
tap on them to open them

currently too small pictures,  don’t always clearly see what is on the photograph.

**Comment by rionita** [comment]
this issue needs to be addressed in both the native apps and the web admin

**Comment by rionita** [comment]
development done, needs to be tested

**Comment by KristiinaKerge** [comment]
fixed

**Comment by lynxlynxlynx** [comment]
it's not fixed on mobile, but it already displays a bigger version than the web-app, so perhaps it's fine.
